#!/bin/bash
# This script compiles the css dependencies for the website.
# Author: Alvin Lin (alvin.lin@stuypulse.com)

lessc styles.less --clean-css="-s0 --advanced" > styles.css
echo "CSS compiled into styles.css"
