  /**
  * Autogenerated, do not edit!
  * @author alvin.lin.dev@gmail.com (Alvin Lin)
  */

module.exports = {
  "wordFrequency": {
    "SANDERS": [
      [
        "people",
        289
      ],
      [
        "country",
        190
      ],
      [
        "think",
        174
      ],
      [
        "secretary",
        137
      ],
      [
        "street",
        96
      ],
      [
        "wall",
        95
      ],
      [
        "president",
        90
      ],
      [
        "believe",
        90
      ],
      [
        "america",
        81
      ],
      [
        "american",
        81
      ]
    ],
    "TRUMP": [
      [
        "people",
        315
      ],
      [
        "country",
        161
      ],
      [
        "think",
        124
      ],
      [
        "many",
        98
      ],
      [
        "great",
        91
      ],
      [
        "tell",
        85
      ],
      [
        "deal",
        73
      ],
      [
        "china",
        62
      ],
      [
        "never",
        61
      ],
      [
        "good",
        57
      ]
    ],
    "CLINTON": [
      [
        "think",
        219
      ],
      [
        "people",
        202
      ],
      [
        "president",
        136
      ],
      [
        "senator",
        106
      ],
      [
        "support",
        79
      ],
      [
        "work",
        71
      ],
      [
        "country",
        70
      ],
      [
        "us",
        69
      ],
      [
        "care",
        68
      ],
      [
        "sanders",
        65
      ]
    ]
  },
  "transcriptLinks": [
    {
      "link": "http://www.nytimes.com/2015/10/14/us/politics/democratic-debate-transcript.html",
      "date": "10/14/2015",
      "party": "Democratic"
    },
    {
      "link": "http://www.nytimes.com/2015/10/29/us/politics/transcript-republican-presidential-debate.html",
      "date": "10/29/2015",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2015/11/11/us/politics/transcript-republican-presidential-debate.html",
      "date": "11/11/2015",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2015/12/16/us/politics/transcript-main-republican-presidential-debate.html",
      "date": "12/16/2015",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/01/15/us/politics/transcript-of-republican-presidential-debate.html",
      "date": "01/15/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/01/18/us/politics/transcript-of-the-democratic-presidential-debate.html",
      "date": "01/18/2016",
      "party": "Democratic"
    },
    {
      "link": "http://www.nytimes.com/2016/01/29/us/politics/republican-presidential-debate-transcript.html",
      "date": "01/29/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/02/26/us/politics/transcript-of-the-republican-presidential-debate-in-houston.html",
      "date": "02/06/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/03/04/us/politics/transcript-of-the-republican-presidential-debate-in-detroit.html",
      "date": "03/04/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/03/11/us/politics/transcript-of-the-republican-presidential-debate-in-florida.html",
      "date": "03/11/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/02/05/us/politics/transcript-of-the-democratic-presidential-debate.html",
      "date": "02/05/2016",
      "party": "Democratic"
    },
    {
      "link": "http://www.nytimes.com/2016/02/07/us/politics/transcript-of-the-republican-presidential-debate-in-new-hampshire.html",
      "date": "02/07/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/02/12/us/politics/transcript-of-the-democratic-presidential-debate-in-milwaukee.html",
      "date": "02/12/2016",
      "party": "Democratic"
    },
    {
      "link": "http://www.nytimes.com/2016/02/14/us/politics/transcript-of-the-republican-presidential-debate.html",
      "date": "02/14/2016",
      "party": "Republican"
    },
    {
      "link": "http://www.nytimes.com/2016/03/07/us/politics/transcript-democratic-presidential-debate.html",
      "date": "03/07/2016",
      "party": "Democratic"
    },
    {
      "link": "http://www.nytimes.com/2016/03/10/us/politics/transcript-democratic-presidential-debate.html",
      "date": "03/10/2016",
      "party": "Democratic"
    }
  ]
};
